### ISSUE TITLE
Missing jar 0.5.1 and 0.5.2 for scala 2.11

### ISSUE THREAD

**Issue by Maatary** [altoo-ag/akka-kryo-serialization#136] opened 2018-09-14 09:50 UTC
Hi could you please the jar for 0.5.1 and 0.5.1 for scala 2.11. So far the only available are for scala 2.12. 

2.11 stop at 0.5.0

**Comment by spaced** [comment] 2019-09-25 07:26
duplicate of #109

**Closed** 2019-09-25 08:26 UTC
